import type { MarketplaceDefinition } from "@/lib/global-marketplace/types";

const DEFAULT_LOGO = "/stores/default.png";

/**
 * Global marketplace registry — configuration-only additions.
 * Wire integrationProviderId to lib/sync when a provider goes live.
 */
export const MARKETPLACE_REGISTRY: Record<string, MarketplaceDefinition> = {
  "amazon-us": {
    id: "amazon-us",
    name: "Amazon US",
    logo: "/stores/amazon.png",
    supportedCountries: ["US", "GLOBAL"],
    supportedLanguages: ["en", "es"],
    supportedCurrencies: ["USD"],
    affiliate: { programId: "amazon-us", network: "amazon-associates", defaultTagEnvKey: "AMAZON_ASSOCIATE_TAG" },
    shipping: { countries: ["US"] },
    categories: ["electronics", "computers", "phones", "gaming", "home"],
    endpoints: { search: "/api/marketplaces/amazon-us/search", product: "/api/marketplaces/amazon-us/product" },
    integrationProviderId: "amazon",
    status: "configured",
  },
  "amazon-uk": {
    id: "amazon-uk",
    name: "Amazon UK",
    logo: "/stores/amazon.png",
    supportedCountries: ["GB", "GLOBAL"],
    supportedLanguages: ["en"],
    supportedCurrencies: ["GBP"],
    affiliate: { programId: "amazon-uk", network: "amazon-associates", defaultTagEnvKey: "AMAZON_UK_ASSOCIATE_TAG" },
    shipping: { countries: ["GB"] },
    categories: ["electronics", "computers", "phones", "gaming", "home"],
    endpoints: { search: "/api/marketplaces/amazon-uk/search", product: "/api/marketplaces/amazon-uk/product" },
    integrationProviderId: "amazon",
    status: "configured",
  },
  "amazon-de": {
    id: "amazon-de",
    name: "Amazon DE",
    logo: "/stores/amazon.png",
    supportedCountries: ["DE", "GLOBAL"],
    supportedLanguages: ["de", "en"],
    supportedCurrencies: ["EUR"],
    affiliate: { programId: "amazon-de", network: "amazon-associates", defaultTagEnvKey: "AMAZON_DE_ASSOCIATE_TAG" },
    shipping: { countries: ["DE"] },
    categories: ["electronics", "computers", "phones", "gaming", "home"],
    endpoints: { search: "/api/marketplaces/amazon-de/search", product: "/api/marketplaces/amazon-de/product" },
    integrationProviderId: "amazon",
    status: "configured",
  },
  "amazon-fr": {
    id: "amazon-fr",
    name: "Amazon FR",
    logo: "/stores/amazon.png",
    supportedCountries: ["FR", "GLOBAL"],
    supportedLanguages: ["fr", "en"],
    supportedCurrencies: ["EUR"],
    affiliate: { programId: "amazon-fr", network: "amazon-associates", defaultTagEnvKey: "AMAZON_FR_ASSOCIATE_TAG" },
    shipping: { countries: ["FR"] },
    categories: ["electronics", "computers", "phones", "gaming", "home"],
    endpoints: { search: "/api/marketplaces/amazon-fr/search", product: "/api/marketplaces/amazon-fr/product" },
    integrationProviderId: "amazon",
    status: "planned",
  },
  "amazon-eg": {
    id: "amazon-eg",
    name: "Amazon.eg",
    logo: "/stores/amazon.png",
    supportedCountries: ["EG", "GLOBAL"],
    supportedLanguages: ["ar", "en"],
    supportedCurrencies: ["EGP"],
    affiliate: { programId: "amazon-eg", network: "amazon-associates" },
    shipping: { countries: ["EG"] },
    categories: ["electronics", "phones", "fashion", "home"],
    endpoints: { search: "/api/marketplaces/amazon-eg/search", product: "/api/marketplaces/amazon-eg/product" },
    integrationProviderId: "amazon",
    status: "planned",
  },
  "amazon-sa": {
    id: "amazon-sa",
    name: "Amazon.sa",
    logo: "/stores/amazon.png",
    supportedCountries: ["SA", "GLOBAL"],
    supportedLanguages: ["ar", "en"],
    supportedCurrencies: ["SAR"],
    affiliate: { programId: "amazon-sa", network: "amazon-associates" },
    shipping: { countries: ["SA"] },
    categories: ["electronics", "phones", "fashion", "home"],
    endpoints: { search: "/api/marketplaces/amazon-sa/search", product: "/api/marketplaces/amazon-sa/product" },
    integrationProviderId: "amazon",
    status: "planned",
  },
  "best-buy": {
    id: "best-buy",
    name: "Best Buy",
    logo: "/stores/best-buy.png",
    supportedCountries: ["US", "CA", "GLOBAL"],
    supportedLanguages: ["en", "fr"],
    supportedCurrencies: ["USD", "CAD"],
    affiliate: { programId: "best-buy", defaultTagEnvKey: "BESTBUY_AFFILIATE_ID" },
    shipping: { countries: ["US", "CA"] },
    categories: ["electronics", "computers", "gaming", "phones"],
    endpoints: { search: "/api/marketplaces/best-buy/search", product: "/api/marketplaces/best-buy/product" },
    integrationProviderId: "best-buy",
    status: "planned",
  },
  walmart: {
    id: "walmart",
    name: "Walmart",
    logo: "/stores/walmart.png",
    supportedCountries: ["US", "GLOBAL"],
    supportedLanguages: ["en", "es"],
    supportedCurrencies: ["USD"],
    affiliate: { programId: "walmart", defaultTagEnvKey: "WALMART_AFFILIATE_ID" },
    shipping: { countries: ["US"] },
    categories: ["electronics", "home", "fashion", "gaming"],
    endpoints: { search: "/api/marketplaces/walmart/search", product: "/api/marketplaces/walmart/product" },
    integrationProviderId: "walmart",
    status: "planned",
  },
  target: {
    id: "target",
    name: "Target",
    logo: DEFAULT_LOGO,
    supportedCountries: ["US", "GLOBAL"],
    supportedLanguages: ["en", "es"],
    supportedCurrencies: ["USD"],
    affiliate: { programId: "target" },
    shipping: { countries: ["US"] },
    categories: ["electronics", "home", "fashion"],
    endpoints: { search: "/api/marketplaces/target/search", product: "/api/marketplaces/target/product" },
    status: "planned",
  },
  newegg: {
    id: "newegg",
    name: "Newegg",
    logo: DEFAULT_LOGO,
    supportedCountries: ["US", "GLOBAL"],
    supportedLanguages: ["en"],
    supportedCurrencies: ["USD"],
    affiliate: { programId: "newegg" },
    shipping: { countries: ["US"] },
    categories: ["computers", "electronics", "gaming"],
    endpoints: { search: "/api/marketplaces/newegg/search", product: "/api/marketplaces/newegg/product" },
    status: "planned",
  },
  "noon-eg": {
    id: "noon-eg",
    name: "Noon Egypt",
    logo: "/stores/noon.png",
    supportedCountries: ["EG", "GLOBAL"],
    supportedLanguages: ["ar", "en"],
    supportedCurrencies: ["EGP"],
    affiliate: { programId: "noon-eg", defaultTagEnvKey: "NOON_AFFILIATE_ID" },
    shipping: { countries: ["EG"] },
    categories: ["electronics", "phones", "fashion", "home"],
    endpoints: { search: "/api/marketplaces/noon-eg/search", product: "/api/marketplaces/noon-eg/product" },
    integrationProviderId: "noon",
    status: "planned",
  },
  "noon-sa": {
    id: "noon-sa",
    name: "Noon KSA",
    logo: "/stores/noon.png",
    supportedCountries: ["SA", "GLOBAL"],
    supportedLanguages: ["ar", "en"],
    supportedCurrencies: ["SAR"],
    affiliate: { programId: "noon-sa", defaultTagEnvKey: "NOON_AFFILIATE_ID" },
    shipping: { countries: ["SA"] },
    categories: ["electronics", "phones", "fashion", "home"],
    endpoints: { search: "/api/marketplaces/noon-sa/search", product: "/api/marketplaces/noon-sa/product" },
    integrationProviderId: "noon",
    status: "planned",
  },
  "noon-ae": {
    id: "noon-ae",
    name: "Noon UAE",
    logo: "/stores/noon.png",
    supportedCountries: ["AE", "GLOBAL"],
    supportedLanguages: ["ar", "en"],
    supportedCurrencies: ["AED"],
    affiliate: { programId: "noon-ae", defaultTagEnvKey: "NOON_AFFILIATE_ID" },
    shipping: { countries: ["AE"] },
    categories: ["electronics", "phones", "fashion", "home"],
    endpoints: { search: "/api/marketplaces/noon-ae/search", product: "/api/marketplaces/noon-ae/product" },
    integrationProviderId: "noon",
    status: "planned",
  },
  "jumia-eg": {
    id: "jumia-eg",
    name: "Jumia Egypt",
    logo: DEFAULT_LOGO,
    supportedCountries: ["EG", "GLOBAL"],
    supportedLanguages: ["ar", "en", "fr"],
    supportedCurrencies: ["EGP"],
    affiliate: { programId: "jumia-eg" },
    shipping: { countries: ["EG"] },
    categories: ["electronics", "phones", "fashion", "home"],
    endpoints: { search: "/api/marketplaces/jumia-eg/search", product: "/api/marketplaces/jumia-eg/product" },
    status: "planned",
  },
  jarir: {
    id: "jarir",
    name: "Jarir",
    logo: DEFAULT_LOGO,
    supportedCountries: ["SA", "AE", "GLOBAL"],
    supportedLanguages: ["ar", "en"],
    supportedCurrencies: ["SAR", "AED"],
    affiliate: { programId: "jarir", defaultTagEnvKey: "JARIR_AFFILIATE_ID" },
    shipping: { countries: ["SA", "AE"] },
    categories: ["electronics", "computers", "phones", "gaming"],
    endpoints: { search: "/api/marketplaces/jarir/search", product: "/api/marketplaces/jarir/product" },
    integrationProviderId: "jarir",
    status: "planned",
  },
  extra: {
    id: "extra",
    name: "eXtra",
    logo: DEFAULT_LOGO,
    supportedCountries: ["SA", "AE", "GLOBAL"],
    supportedLanguages: ["ar", "en"],
    supportedCurrencies: ["SAR", "AED"],
    affiliate: { programId: "extra", defaultTagEnvKey: "EXTRA_AFFILIATE_ID" },
    shipping: { countries: ["SA", "AE"] },
    categories: ["electronics", "computers", "phones", "home"],
    endpoints: { search: "/api/marketplaces/extra/search", product: "/api/marketplaces/extra/product" },
    integrationProviderId: "extra",
    status: "planned",
  },
  currys: {
    id: "currys",
    name: "Currys",
    logo: DEFAULT_LOGO,
    supportedCountries: ["GB", "GLOBAL"],
    supportedLanguages: ["en"],
    supportedCurrencies: ["GBP"],
    affiliate: { programId: "currys" },
    shipping: { countries: ["GB"] },
    categories: ["electronics", "computers", "gaming", "home"],
    endpoints: { search: "/api/marketplaces/currys/search", product: "/api/marketplaces/currys/product" },
    status: "planned",
  },
  argos: {
    id: "argos",
    name: "Argos",
    logo: DEFAULT_LOGO,
    supportedCountries: ["GB", "GLOBAL"],
    supportedLanguages: ["en"],
    supportedCurrencies: ["GBP"],
    affiliate: { programId: "argos" },
    shipping: { countries: ["GB"] },
    categories: ["electronics", "home", "gaming", "fashion"],
    endpoints: { search: "/api/marketplaces/argos/search", product: "/api/marketplaces/argos/product" },
    status: "planned",
  },
  mediamarkt: {
    id: "mediamarkt",
    name: "MediaMarkt",
    logo: DEFAULT_LOGO,
    supportedCountries: ["DE", "GLOBAL"],
    supportedLanguages: ["de", "en"],
    supportedCurrencies: ["EUR"],
    affiliate: { programId: "mediamarkt" },
    shipping: { countries: ["DE"] },
    categories: ["electronics", "computers", "gaming", "home"],
    endpoints: { search: "/api/marketplaces/mediamarkt/search", product: "/api/marketplaces/mediamarkt/product" },
    status: "planned",
  },
  saturn: {
    id: "saturn",
    name: "Saturn",
    logo: DEFAULT_LOGO,
    supportedCountries: ["DE", "GLOBAL"],
    supportedLanguages: ["de", "en"],
    supportedCurrencies: ["EUR"],
    affiliate: { programId: "saturn" },
    shipping: { countries: ["DE"] },
    categories: ["electronics", "computers", "gaming", "home"],
    endpoints: { search: "/api/marketplaces/saturn/search", product: "/api/marketplaces/saturn/product" },
    status: "planned",
  },
  fnac: {
    id: "fnac",
    name: "Fnac",
    logo: DEFAULT_LOGO,
    supportedCountries: ["FR", "GLOBAL"],
    supportedLanguages: ["fr", "en"],
    supportedCurrencies: ["EUR"],
    affiliate: { programId: "fnac" },
    shipping: { countries: ["FR"] },
    categories: ["electronics", "computers", "gaming", "books"],
    endpoints: { search: "/api/marketplaces/fnac/search", product: "/api/marketplaces/fnac/product" },
    status: "planned",
  },
  cdiscount: {
    id: "cdiscount",
    name: "Cdiscount",
    logo: DEFAULT_LOGO,
    supportedCountries: ["FR", "GLOBAL"],
    supportedLanguages: ["fr", "en"],
    supportedCurrencies: ["EUR"],
    affiliate: { programId: "cdiscount" },
    shipping: { countries: ["FR"] },
    categories: ["electronics", "home", "gaming", "fashion"],
    endpoints: { search: "/api/marketplaces/cdiscount/search", product: "/api/marketplaces/cdiscount/product" },
    status: "planned",
  },
  aliexpress: {
    id: "aliexpress",
    name: "AliExpress",
    logo: "/stores/aliexpress.png",
    supportedCountries: ["US", "GB", "DE", "FR", "AE", "SA", "EG", "CA", "GLOBAL"],
    supportedLanguages: ["en", "ar", "fr", "de", "es"],
    supportedCurrencies: ["USD", "EUR", "GBP", "AED", "SAR", "EGP", "CAD"],
    affiliate: { programId: "aliexpress", defaultTagEnvKey: "ALIEXPRESS_TRACKING_ID" },
    shipping: { countries: ["US", "GB", "DE", "FR", "AE", "SA", "EG", "CA"], notes: "Cross-border shipping varies by seller" },
    categories: ["electronics", "phones", "fashion", "home", "gaming"],
    endpoints: { search: "/api/marketplaces/aliexpress/search", product: "/api/marketplaces/aliexpress/product" },
    integrationProviderId: "aliexpress",
    status: "active",
  },
  ebay: {
    id: "ebay",
    name: "eBay",
    logo: "/stores/ebay.png",
    supportedCountries: ["US", "GB", "DE", "CA", "GLOBAL"],
    supportedLanguages: ["en", "de", "fr", "es"],
    supportedCurrencies: ["USD", "GBP", "EUR", "CAD"],
    affiliate: { programId: "ebay", defaultTagEnvKey: "EBAY_CAMPAIGN_ID" },
    shipping: { countries: ["US", "GB", "DE", "CA"] },
    categories: ["electronics", "computers", "phones", "gaming", "fashion"],
    endpoints: { search: "/api/marketplaces/ebay/search", product: "/api/marketplaces/ebay/product" },
    integrationProviderId: "ebay",
    status: "active",
  },
};

export function getMarketplaceById(id: string): MarketplaceDefinition | null {
  return MARKETPLACE_REGISTRY[id] ?? null;
}

export function listMarketplaces(): MarketplaceDefinition[] {
  return Object.values(MARKETPLACE_REGISTRY);
}
